Added UI tests
MyatThuKo/CSc456-FlashCardApp-Final-Project pull request #18
Opened 2023-05-01 01:00 UTC by krosario23

## Links to Asana tickets

**Login**
https://app.asana.com/0/1204171546585013/1204501394819402

**Sign-up**
https://app.asana.com/0/1204171546585013/1204501394819406

**Reset Password**
https://app.asana.com/0/1204171546585013/1204501394819408

## Description

Added UI tests for sign-up, login, and reset password components. All three tests succeed when run on my Macbook.

2023-05-01 02:46 UTC, MyatThuKo requested changes

2023-05-01 02:46 UTC, MyatThuKo commented on StudySwift/StudySwiftUITests/StudySwiftUITests.swift
> +        passwordField.typeText("password")
I'd change this password to one that contains special characters and numbers in it. For example, P@ssword12356.

2023-05-01 02:46 UTC, MyatThuKo commented on StudySwift/StudySwiftUITests/StudySwiftUITests.swift
> +        confirmField.typeText("password")
The above comment goes the same here.

2023-05-01 20:11 UTC, MyatThuKo approved these changes
Tested and you can merge this PR without doing any changes I suggested but just preference on those changes and not blocking.

2023-05-01 21:11 UTC, cyanChill commented
Backend tests actions are failing since the `GOOGLE_SERVICES_JSON` repository secret isn't defined (not sure if it's running off of the actions file in the main repository or on the fork).

2023-05-02 02:12 UTC, cyanChill reviewed
Got tests working and they all pass.

**A problem I see is that since your branch currently doesn't contain any of the hardcoded screens since those screens were only pushed from a branch to another branch, they will fail if run normally.**
- **I might suggest pushing this to the branch where the hard coded screens were finalized.**

2023-05-13 23:12 UTC, merged